services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./index.php:/var/www/html/index.php
      - ./scripts:/var/www/html/scripts
      - ./uploads:/var/www/html/uploads
    depends_on:
      - mysql
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/uploads &&
             chmod -R 755 /var/www/html/uploads &&
             apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fireguard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
